### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by VovaTimoshevskiy** [VovaTimoshevskiy/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by VovaTimosh** [comment]
December 2, 2013

Rick takes Morty on a trip to another dimension to find seeds for "mega-trees," while Jerry and Beth argue over Rick's influence on their son.

December 9, 2013

Rick creates a device to make family dog Snuffles smarter, but it goes poorly. Rick and Morty invade the dreams of Morty's math teacher.

July 26, 2015

Rick unfreezes time, but since he, Morty and Summer have been living for so long on frozen time, a parallel dimension develops.

August 23, 2015

When an alien entity appears with musical demands, Rick and Morty call on Ice-T to help them write a tune for an intergalactic song competition.

October 1, 2017

The president needs help from Rick and Morty, prompting a bit of a confrontation. Beth begins to suspect that she may be a clone.
